# Generated by Django 2.2.6 on 2020-05-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_auto_20200527_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
    ]
