# Generated by Django 2.2.6 on 2020-05-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_auto_20200527_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='orders',
        ),
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(to='useraccount.Order'),
        ),
    ]
