# Generated by Django 2.2.6 on 2020-05-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('trips', '0002_auto_20200517_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vendors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Vendor'),
        ),
    ]
