# Generated by Django 2.2.6 on 2020-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
