# Generated by Django 2.2.6 on 2020-05-20 18:01

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_profile_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=pyuploadcare.dj.models.ImageField(default=None),
            preserve_default=False,
        ),
    ]
