# Generated by Django 2.2.6 on 2020-05-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20200520_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
