# Generated by Django 2.2.6 on 2020-05-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='vendors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
    ]
